//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public System.Guid Id { get; set; }
        public System.Guid GuidGroup { get; set; }
        public string AuditType { get; set; }
        public string TableName { get; set; }
        public string PK { get; set; }
        public string ColumnName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime Date { get; set; }
        public string UserId { get; set; }
    }
}
