//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelData
    {
        public int id { get; set; }
        public string prop1 { get; set; }
        public Nullable<double> prop2 { get; set; }
        public Nullable<double> prop3 { get; set; }
    }
}
