//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_PROVINCIA
    {
        public int PR_Id { get; set; }
        public int PA_Id { get; set; }
        public string PR_Descripcion { get; set; }
    
        public virtual PA_PAISES PA_PAISES { get; set; }
    }
}
