//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAX_USUARIO()
        {
            this.SAX_USUARIO_ROL = new HashSet<SAX_USUARIO_ROL>();
        }
    
        public string US_ID_USUARIO { get; set; }
        public string US_COD_USUARIO { get; set; }
        public string US_NOMBRE { get; set; }
        public int US_ACTIVO { get; set; }
        public System.DateTime US_FECHA_CREACION { get; set; }
        public string US_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> US_FECHA_MOD { get; set; }
        public string US_USUARIO_MOD { get; set; }
        public Nullable<System.DateTime> US_ULTIMO_ACCESO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAX_USUARIO_ROL> SAX_USUARIO_ROL { get; set; }
    }
}
