//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_MODULO_ROL
    {
        public int MR_ID_MODULO_ROL { get; set; }
        public int MO_ID_MODULO { get; set; }
        public string RL_ID_ROL { get; set; }
        public int MR_ESTATUS { get; set; }
        public System.DateTime MR_FECHA_CREACION { get; set; }
        public string MR_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> MR_FECHA_MOD { get; set; }
        public string MR_USUARIO_MOD { get; set; }
        public Nullable<System.DateTime> MR_ULTIMO_ACCESO { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual SAX_MODULO SAX_MODULO { get; set; }
    }
}
