//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_PARAMETRO_ARCHIVO
    {
        public int ID_PARAMETRO_ARCHIVO { get; set; }
        public string IDPROCESS { get; set; }
        public string FILENAME { get; set; }
        public string FILESERVERPATH { get; set; }
        public string FILEOBJECT { get; set; }
        public string USERBATCH { get; set; }
        public System.DateTime DATEPROCESS { get; set; }
        public System.DateTime DATEPMODIFY { get; set; }
        public string USERMODIFY { get; set; }
    }
}
