//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_AREA_CENCOSTO
    {
        public int AD_ID_REGISTRO { get; set; }
        public int CA_COD_AREA { get; set; }
        public int EC_ID_REGISTRO { get; set; }
        public int AD_ESTATUS { get; set; }
        public System.DateTime AD_FECHA_CREACION { get; set; }
        public string AD_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> AD_FECHA_MOD { get; set; }
        public string AD_USUARIO_MOD { get; set; }
    
        public virtual SAX_AREA_OPERATIVA SAX_AREA_OPERATIVA { get; set; }
        public virtual SAX_EMPRESA_CENTRO SAX_EMPRESA_CENTRO { get; set; }
    }
}
