//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_MODULO_ROL
    {
        public int MR_ID_MODULO_ROL { get; set; }
        public int MO_ID_MODULO { get; set; }
        public int RL_ID_ROL { get; set; }
        public int MR_ESTATUS { get; set; }
        public System.DateTime MR_FECHA_CREACION { get; set; }
        public string MR_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> MR_FECHA_MOD { get; set; }
        public string MR_USUARIO_MOD { get; set; }
        public Nullable<System.DateTime> MR_ULTIMO_ACCESO { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual SAX_MODULO SAX_MODULO { get; set; }
        public virtual SAX_ROLES SAX_ROLES { get; set; }
    }
}
