//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_COMPROBANTE_DETALLE
    {
        public int TD_ID_DETALLE { get; set; }
        public int TC_ID_COMPROBANTE { get; set; }
        public int PA_REGISTRO { get; set; }
        public System.DateTime TD_FECHA_CREACION { get; set; }
        public string TD_USUARIO_CREACION { get; set; }
        public System.DateTime TD_FECHA_MOD { get; set; }
        public string TD_USUARIO_MOD { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual SAX_COMPROBANTE SAX_COMPROBANTE { get; set; }
        public virtual SAX_PARTIDAS SAX_PARTIDAS { get; set; }
    }
}
