//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_LOG_USUARIO
    {
        public int LG_SECUENCIA { get; set; }
        public string US_ID_USUARIO { get; set; }
        public System.DateTime LG_FECHA { get; set; }
        public System.TimeSpan LG_HORA { get; set; }
        public string LG_PROCESO { get; set; }
        public string LG_OBJETO { get; set; }
        public string LG_TABLA { get; set; }
        public string LG_OPERACION { get; set; }
        public string LG_ACCION { get; set; }
        public System.DateTime LG_FECHA_CREA { get; set; }
        public string LG_USUARIO_CREA { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
