//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_CUENTA_CONTABLE
    {
        public int CO_ID_CUENTA_CONTABLE { get; set; }
        public int CO_INSTITUCION { get; set; }
        public int CE_ID_EMPRESA { get; set; }
        public string CO_CUENTA_CONTABLE { get; set; }
        public string CO_COD_AUXILIAR { get; set; }
        public string CO_NUM_AUXILIAR { get; set; }
        public string CO_NOM_CUENTA { get; set; }
        public string CO_NOM_AUXILIAR { get; set; }
        public string CO_COD_CONCILIA { get; set; }
        public string CO_COD_NATURALEZA { get; set; }
        public string CO_COD_AREA { get; set; }
        public int CO_ESTATUS { get; set; }
        public System.DateTime CO_FECHA_CREACION { get; set; }
        public string CO_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> CO_FECHA_MOD { get; set; }
        public string CO_USUARIO_MOD { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual SAX_EMPRESA SAX_EMPRESA { get; set; }
    }
}
