//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_CALENDARIO
    {
        public int CA_ID_CALENDA { get; set; }
        public string CA_ANIO { get; set; }
        public string CA_MES { get; set; }
        public string CA_VECTOR { get; set; }
        public int CA_ESTATUS { get; set; }
        public Nullable<System.DateTime> CA_FECHA_CREACION { get; set; }
        public string CA_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> CA_FECHA_MOD { get; set; }
        public string CA_USUARIO_MOD { get; set; }
    }
}
