//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_USUARIO
    {
        public string US_COD_USUARIO { get; set; }
        public string US_NOMBRE { get; set; }
        public string US_APELLIDO_PATERNO { get; set; }
        public string US_APELLIDO_MATERNO { get; set; }
        public string US_ACTIVO { get; set; }
        public System.DateTime US_FECHA_CREACION { get; set; }
        public string US_USUARIO_CREACION { get; set; }
        public System.DateTime US_FECHA_MOD { get; set; }
        public string US_USUARIO_MOD { get; set; }
        public System.DateTime US_ULTIMO_ACCESO { get; set; }
    }
}
