//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_ROLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAX_ROLES()
        {
            this.SAX_MODULO_ROL = new HashSet<SAX_MODULO_ROL>();
            this.SAX_USUARIO_ROL = new HashSet<SAX_USUARIO_ROL>();
        }
    
        public int RL_ID_ROL { get; set; }
        public string RL_NOMBRE_ROL { get; set; }
        public string RL_DESCRIPCION_ROL { get; set; }
        public int RL_ESTATUS_ROL { get; set; }
        public System.DateTime RL_FECHA_CREACION { get; set; }
        public string RL_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> RL_FECHA_MOD { get; set; }
        public string RL_USUARIO_MOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAX_MODULO_ROL> SAX_MODULO_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAX_USUARIO_ROL> SAX_USUARIO_ROL { get; set; }
    }
}
