//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_MODULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAX_MODULO()
        {
            this.SAX_MODULO_ROL = new HashSet<SAX_MODULO_ROL>();
        }
    
        public int MO_ID_MODULO { get; set; }
        public string MO_MODULO { get; set; }
        public string MO_PATH { get; set; }
        public string MO_DESCRIPCION { get; set; }
        public int MO_ESTATUS { get; set; }
        public System.DateTime MO_FECHA_CREACION { get; set; }
        public string MO_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> MO_FECHA_MOD { get; set; }
        public string MO_USUARIO_MOD { get; set; }
        public Nullable<System.DateTime> MO_ULTIMO_ACCESO { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAX_MODULO_ROL> SAX_MODULO_ROL { get; set; }
    }
}
