//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_USUARIO_AREA
    {
        public int UA_ID_USUARIO_AREA { get; set; }
        public string US_ID_USUARIO { get; set; }
        public int CA_ID_AREA { get; set; }
        public int UA_ESTATUS { get; set; }
        public System.DateTime UA_FECHA_CREACION { get; set; }
        public string UA_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> UA_FECHA_MOD { get; set; }
        public string UA_USUARIO_MOD { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
