//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_COMPROBANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAX_COMPROBANTE()
        {
            this.SAX_COMPROBANTE_DETALLE = new HashSet<SAX_COMPROBANTE_DETALLE>();
        }
    
        public int TC_ID_COMPROBANTE { get; set; }
        public string TC_COD_OPERACION { get; set; }
        public System.DateTime TC_FECHA_PROCESO { get; set; }
        public int TC_TOTAL_REGISTRO { get; set; }
        public decimal TC_TOTAL_DEBITO { get; set; }
        public decimal TC_TOTAL_CREDITO { get; set; }
        public decimal TC_TOTAL { get; set; }
        public string TC_ESTATUS { get; set; }
        public System.DateTime TC_FECHA_CREACION { get; set; }
        public string TC_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> TC_FECHA_APROBACION { get; set; }
        public string TC_USUARIO_APROBADOR { get; set; }
        public Nullable<System.DateTime> TC_FECHA_MOD { get; set; }
        public string TC_USUARIO_MOD { get; set; }
        public string TC_COD_COMPROBANTE { get; set; }
        public Nullable<System.DateTime> TC_FECHA_RECHAZO { get; set; }
        public string TC_USUARIO_RECHAZO { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual AspNetUsers AspNetUsers3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAX_COMPROBANTE_DETALLE> SAX_COMPROBANTE_DETALLE { get; set; }
    }
}
