//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_LOG_USUARIO
    {
        public int LG_SECUENCIA { get; set; }
        public string LG_COD_USUARIO { get; set; }
        public System.DateTime LG_FECHA { get; set; }
        public System.TimeSpan LG_HORA { get; set; }
        public string LG_PROCESO { get; set; }
        public string LG_OBJETO { get; set; }
        public string LG_TABLA { get; set; }
        public string LG_OPERACION { get; set; }
        public string LG_ACCION { get; set; }
        public System.DateTime LG_FECHA_CREA { get; set; }
        public string LG_USUARIO_CREA { get; set; }
    }
}
