//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_SALDO_CONTABLE
    {
        public int SA_ID_SALDO_CONTABLE { get; set; }
        public int SA_INSTITUCION { get; set; }
        public int CO_ID_CUENTA_CONTABLE { get; set; }
        public int CC_ID_MONEDA { get; set; }
        public System.DateTime SA_FECHA_CORTE { get; set; }
        public decimal SA_SALDOS { get; set; }
        public int SA_ESTATUS { get; set; }
        public System.DateTime SA_FECHA_CREACION { get; set; }
        public string SA_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> SA_FECHA_MOD { get; set; }
        public string SA_USUARIO_MOD { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual SAX_CUENTA_CONTABLE SAX_CUENTA_CONTABLE { get; set; }
        public virtual SAX_MONEDA SAX_MONEDA { get; set; }
    }
}
