//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_USUARIO_EMPRESA
    {
        public string US_COD_USUARIO { get; set; }
        public string CE_COD_EMPRESA { get; set; }
        public int UE_ESTATUS { get; set; }
        public System.DateTime UE_FECHA_CREACION { get; set; }
        public string UE_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> UE_FECHA_MOD { get; set; }
        public string UE_USUARIO_MOD { get; set; }
    
        public virtual SAX_EMPRESA SAX_EMPRESA { get; set; }
        public virtual SAX_USUARIO SAX_USUARIO { get; set; }
    }
}
