//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_MONEDA
    {
        public int CC_ID_MONEDA { get; set; }
        public string CC_NUM_MONEDA { get; set; }
        public string CC_DESC_MONEDA { get; set; }
        public string CC_COD_CURRENCY { get; set; }
        public string CC_ESTATUS { get; set; }
        public System.DateTime CC_FECHA_CREACION { get; set; }
        public string CC_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> CC_FECHA_MOD { get; set; }
        public string CC_USUARIO_MOD { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
