//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_COMPROBANTE_DETALLE
    {
        public int TD_ID_DETALLE { get; set; }
        public int TC_ID_COMPROBANTE { get; set; }
        public int PA_REGISTRO { get; set; }
        public System.DateTime TD_FECHA_CREACION { get; set; }
        public string TD_USUARIO_CREACION { get; set; }
        public System.DateTime TD_FECHA_MOD { get; set; }
        public string TD_USUARIO_MOD { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual SAX_COMPROBANTE SAX_COMPROBANTE { get; set; }
        public virtual SAX_PARTIDAS SAX_PARTIDAS { get; set; }
    }
}
