//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_PARAMETRO_ARCHIVO
    {
        public int ID_PARAMETRO_ARCHIVO { get; set; }
        public string IDPROCESS { get; set; }
        public string FILENAME { get; set; }
        public string FILESERVERPATH { get; set; }
        public string FILEOBJECT { get; set; }
        public string USERBATCH { get; set; }
        public System.DateTime DATEPROCESS { get; set; }
        public System.DateTime DATEPMODIFY { get; set; }
        public string USERMODIFY { get; set; }
    }
}
