//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_CATALOGO_DETALLE
    {
        public int CD_ID_CATALOGO_DETALLE { get; set; }
        public int CA_ID_CATALOGO { get; set; }
        public int CD_TABLA { get; set; }
        public string CD_VALOR { get; set; }
        public int CD_ESTATUS { get; set; }
        public System.DateTime CD_FECHA_CREACION { get; set; }
        public string CD_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> CD_FECHA_MOD { get; set; }
        public string CD_USUARIO_MOD { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual SAX_CATALOGO SAX_CATALOGO { get; set; }
    }
}
