//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_EVENTO_TEMP
    {
        public int EV_COD_EVENTO_TEMP { get; set; }
        public int EV_COD_EVENTO { get; set; }
        public int CE_ID_EMPRESA { get; set; }
        public int EV_ID_AREA { get; set; }
        public string EV_DESCRIPCION_EVENTO { get; set; }
        public string EV_CUENTA_DEBITO { get; set; }
        public string EV_CUENTA_CREDITO { get; set; }
        public string EV_REFERENCIA { get; set; }
        public string EV_ESTATUS_ACCION { get; set; }
        public int EV_ESTATUS { get; set; }
        public System.DateTime EV_FECHA_CREACION { get; set; }
        public string EV_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> EV_FECHA_MOD { get; set; }
        public string EV_USUARIO_MOD { get; set; }
        public Nullable<System.DateTime> EV_FECHA_APROBACION { get; set; }
        public string EV_USUARIO_APROBADOR { get; set; }
    
        public virtual SAX_EVENTO SAX_EVENTO { get; set; }
    }
}
