//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAX_DIAS_FERIADOS
    {
        public int CD_ANNIO { get; set; }
        public string CD_MES { get; set; }
        public string CD_CALENDARIO { get; set; }
        public string CD_ESTATUS { get; set; }
        public System.DateTime CD_FECHA_CREACION { get; set; }
        public string CD_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> CD_FECHA_MOD { get; set; }
        public string CD_USUARIO_MOD { get; set; }
    }
}
