//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_Users
    {
        public int USR_Id { get; set; }
        public string USR_Name { get; set; }
        public Nullable<System.DateTime> USR_RegistrationDate { get; set; }
    }
}
