//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_EmpresaAreasCentroCosto
    {
        public string EmpresaDesc { get; set; }
        public string AreaDesc { get; set; }
        public string CentroCostoDesc { get; set; }
        public int IdArea { get; set; }
        public int IdEmpresa { get; set; }
        public int IdCentroCosto { get; set; }
    }
}
