//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banistmo.Sax.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_EmpresaAreasCentroCosto
    {
        public string EmpresaDesc { get; set; }
        public string AreaDesc { get; set; }
        public string CentroCostoDesc { get; set; }
        public int IdArea { get; set; }
        public int IdEmpresa { get; set; }
        public int IdCentroCosto { get; set; }
    }
}
