USE [SAXWDDB ]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_AREA_CENCOSTO]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_AREA_CENCOSTO]
GO

CREATE TABLE [dbo].[SAX_AREA_CENCOSTO](
	[AD_COD_AREA]			[varchar]	(5) NOT NULL,
	[AD_COD_EMPRESA]		[varchar]	(5) NOT NULL,
	[AD_CENCOSTO_ORIGEN]	[varchar]	(5) NOT NULL,
	[AD_ESTATUS	]			[char]		(1) NULL,
	[AD_FECHA_CREACION]		[datetime]	NOT NULL,
	[AD_USUARIO_CREACION]	[varchar]	(8) NOT NULL,
	[AD_FECHA_MOD]			[datetime]	NULL,
	[AD_USUARIO_MOD]		[varchar]	(8) NULL,

	 CONSTRAINT [PK_AREA_CENCOSTO] UNIQUE CLUSTERED 
	(
		[AD_COD_AREA],[AD_COD_EMPRESA] ASC
	)WITH (PAD_INDEX  = OFF, 	STATISTICS_NORECOMPUTE  = OFF, 
	IGNORE_DUP_KEY = OFF, 	ALLOW_ROW_LOCKS  = ON, 	ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	CREATE NONCLUSTERED INDEX IDX_AREA_CENCOSTO ON  SAX_AREA_CENCOSTO(AD_COD_AREA,AD_COD_EMPRESA,AD_CENCOSTO_ORIGEN)

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_AREA_OPERATIVA]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_AREA_OPERATIVA]
GO

CREATE TABLE [dbo].[SAX_AREA_OPERATIVA](
	[CA_COD_AREA]			[varchar]	(5)		NOT NULL,
	[CA_NOMBRE]				[varchar]	(60)	NOT NULL,
	[CA_DESCRIPCION]		[varchar]	(100)	NOT NULL,
	[CA_ESTATUS]			[char]		(1)		NULL,
	[CA_FECHA_CREACION]		[datetime]			NOT NULL,
	[CA_USUARIO_CREACION]	[varchar]	(8)		NOT NULL,
	[CA_FECHA_MOD]			[datetime]			NULL,
	[CA_USUARIO_MOD]		[varchar]	(8)		NULL,

	 CONSTRAINT [PK_AREA_OPERATIVA] PRIMARY KEY CLUSTERED 
	(
		[CA_COD_AREA]  ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_CATALOGO]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_CATALOGO]
GO

CREATE TABLE [dbo].[SAX_CATALOGO](
	[CA_CODIGO]				[int] identity	NOT NULL,
	[CA_TABLA]				[varchar](30)	NOT NULL,
	[CA_DESCRIPCION]		[varchar](60)	NULL,
	[CA_FECHA_CREACION]		[datetime]		NOT NULL,
	[CA_USUARIO_CREACION]	[varchar](8)	NOT NULL,
	[CA_FECHA_MOD]			[datetime]		NULL,
	[CA_USUARIO_MOD]		[varchar](8)	NULL,

	 CONSTRAINT [PK_CATALOGO] PRIMARY KEY CLUSTERED 
	(
		[CA_CODIGO] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	CREATE NONCLUSTERED INDEX IDX_CATALOGO ON  SAX_CATALOGO(CA_CODIGO,CA_TABLA)

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_CATALOGO_DETALLE]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_CATALOGO_DETALLE]
GO

CREATE TABLE [dbo].[SAX_CATALOGO_DETALLE](
	[CD_TABLA]				[int]			NOT NULL,
	[CD_CODIGO]				[varchar](10)	NOT NULL,
	[CD_VALOR]				[varchar](60)	NOT NULL,
	[CD_ESTADO]				[char](1)		NOT NULL,
	[CD_FECHA_CREACION]		[datetime]		NOT NULL,
	[CD_USUARIO_CREACION]	[varchar](8)	NOT NULL,
	[CD_FECHA_MOD]			[datetime]		NULL,
	[CD_USUARIO_MOD]		[varchar](8)	NULL

	 CONSTRAINT [PK_CATALOGO_DETALLE] PRIMARY KEY CLUSTERED 
	(
		[CD_TABLA], [CD_CODIGO]  ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_CENTRO_COSTO]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_CENTRO_COSTO]
GO

CREATE TABLE [dbo].[SAX_CENTRO_COSTO](
	[CC_COD_EMPRESA]		[varchar](5)	NOT NULL,
	[CC_CENTRO_COSTO]		[varchar](5)	NOT NULL,
	[CC_NOMBRE]				[varchar](60)	NOT NULL,
	[CC_DESCRIPCION]		[varchar](100)  NOT NULL,
	[CC_ESTATUS]			[char](1)		NULL,
	[CC_FECHA_CREACION]		[datetime]		NOT NULL,
	[CC_USUARIO_CREACION]	[varchar](8)	NOT NULL,
	[CC_FECHA_MOD]			[datetime]		NULL,
	[CC_USUARIO_MOD]		[varchar](8)	NULL,

	 CONSTRAINT [PK_CENTRO_COSTO] UNIQUE CLUSTERED
	(
		[CC_CENTRO_COSTO]  ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	CREATE NONCLUSTERED INDEX IDX_EMPRESA ON  SAX_CENTRO_COSTO(CC_COD_EMPRESA, CC_CENTRO_COSTO)

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_CONCEPTO_COSTO]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_CONCEPTO_COSTO]
GO

CREATE TABLE [dbo].[SAX_CONCEPTO_COSTO](
	[CC_COD_EMPRESA]		[varchar](5)	NOT NULL,
	[CC_NUM_CONCEPTO]		[varchar](10)	NOT NULL,
	[CC_CUENTA_MAYOR]		[varchar](16)	NOT NULL,
	[CC_DESCRIPCION]		[varchar](100)  NOT NULL,
	[CC_ESTATUS]			[char](1)		NULL,
	[CC_FECHA_CREACION]		[datetime]		NOT NULL,
	[CC_USUARIO_CREACION]	[varchar](8)	NOT NULL,
	[CC_FECHA_MOD]			[datetime]		NULL,
	[CC_USUARIO_MOD]		[varchar](8)	NULL,

	 CONSTRAINT [PK_CONCEPTO_COSTO] UNIQUE CLUSTERED
	(
		[CC_NUM_CONCEPTO],[CC_CUENTA_MAYOR]  ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	CREATE NONCLUSTERED INDEX IDX_CONCEPTO_COSTO ON  SAX_CONCEPTO_COSTO([CC_COD_EMPRESA],[CC_NUM_CONCEPTO],[CC_CUENTA_MAYOR])

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_CUENTA_CONTABLE]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_CUENTA_CONTABLE]
GO

CREATE TABLE [dbo].[SAX_CUENTA_CONTABLE](
	[CO_INSTITUCION]		[int]			NOT NULL,
	[CO_COD_EMPRESA]		[varchar] (5)	NOT NULL,
	[CO_CUENTA_CONTABLE]	[varchar] (14)	NOT NULL,
	[CO_COD_AUXILIAR]		[varchar] (3)	NOT NULL,
	[CO_NUM_AUXILIAR]		[varchar] (13)	NOT NULL,	
	[CO_NOM_CUENTA]			[varchar] (60)	NOT NULL,
	[CO_NOM_AUXILIAR]		[varchar] (60)	NOT NULL,
	[CO_COD_CONCILIA]		[char] (1)		NULL,
	[CO_COD_NATURALEZA]		[char] (1)		NULL,
	[CO_COD_AREA]			[varchar] (5)	NULL,
	[CO_ESTATUS]			[varchar] (1)	NOT NULL,
	[CO_FECHA_CREACION]		[datetime]		NOT NULL,
	[CO_USUARIO_CREACION]	[varchar] (8)	NOT NULL,
	[CO_FECHA_MOD]			[datetime]		NULL,
	[CO_USUARIO_MOD]		[varchar] (8)	NULL

	 CONSTRAINT [PK_CUENTA_CONTABLE] UNIQUE CLUSTERED 
	(
		[CO_INSTITUCION],[CO_COD_EMPRESA],[CO_CUENTA_CONTABLE],[CO_COD_AUXILIAR],[CO_NUM_AUXILIAR] ASC
	)
	WITH (PAD_INDEX  = OFF, 	STATISTICS_NORECOMPUTE  = OFF, 
	IGNORE_DUP_KEY = OFF, 	ALLOW_ROW_LOCKS  = ON, 	ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	CREATE NONCLUSTERED INDEX IDX_CUENTA_CONTABLE ON  SAX_CUENTA_CONTABLE([CO_COD_EMPRESA],[CO_CUENTA_CONTABLE],[CO_COD_AUXILIAR],[CO_NUM_AUXILIAR])

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_EMPRESA]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_EMPRESA]
GO

CREATE TABLE [dbo].[SAX_EMPRESA](
	[CE_COD_EMPRESA]		[varchar](5)	NOT NULL,
	[CE_NOMBRE]				[varchar](60)	NOT NULL,
	[CE_DESCRIPCION]		[varchar](100)	NOT NULL,
	[CE_ESTATUS]			[char](1)		NULL,
	[CE_FECHA_CREACION]		[datetime]		NOT NULL,
	[CE_USUARIO_CREACION]	[varchar](8)	NOT NULL,
	[CE_FECHA_MOD]			[datetime]		NULL,
	[CE_USUARIO_MOD]		[varchar](8)	NULL,

	 CONSTRAINT [PK_EMPRESA] PRIMARY KEY CLUSTERED 
	(
		[CE_COD_EMPRESA]  ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_EVENTO]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_EVENTO]
GO

CREATE TABLE [dbo].[SAX_EVENTO](
	[EV_COD_EMPRESA]		[varchar] (5)		NOT NULL,
	[EV_COD_AREA]			[varchar] (5)		NOT NULL,	
	[EV_COD_EVENTO]			[varchar] (10)	NOT NULL,
	[EV_DESCRIPCION_EVENTO]	[varchar] (100)	NOT NULL,
	[EV_CUENTA_DEBITO]		[varchar] (14)	NOT NULL,
	[EV_COD_AUXILIARD]		[varchar] (3)		NOT NULL,
	[EV_NUM_AUXILIARD]		[varchar] (13)	NOT NULL,
	[EV_CUENTA_CREDITO]		[varchar] (14)	NOT NULL,
	[EV_COD_AUXILIARC]		[varchar] (3)		NOT NULL,
	[EV_NUM_AUXILIARC]		[varchar] (13)	NOT NULL,
	[EV_REFERENCIA]			[varchar] (1)		NOT NULL,
	[EV_TIPO_ACCION]		[varchar] (15)	NOT NULL,
	[EV_ESTATUS_ACCION]		[varchar] (15)	NOT NULL,
	[EV_ESTATUS]			[char] (1)		NOT NULL,
	[EV_FECHA_CREACION]		[datetime]		NOT NULL,
	[EV_USUARIO_CREACION]	[varchar] (8)	NOT NULL,
	[EV_FECHA_MOD]			[datetime]		NULL,
	[EV_USUARIO_MOD]		[varchar] (8)	NULL,
	[EV_FECHA_APROBACION]	[datetime]		NULL,
	[EV_USUARIO_APROBADOR]	[varchar] (8)	NULL,
	
	 CONSTRAINT [PK_EVENTO] UNIQUE CLUSTERED 
	(
		[EV_COD_EMPRESA],[EV_COD_EVENTO] ASC
	)WITH (PAD_INDEX  = OFF, 
	STATISTICS_NORECOMPUTE  = OFF, 	IGNORE_DUP_KEY = OFF, 	ALLOW_ROW_LOCKS  = ON, 	ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_REGISTRO_CARGA]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_REGISTRO_CARGA]
GO

CREATE TABLE [dbo].[SAX_REGISTRO_CARGA](
	[RC_COD_USUARIO]		[varchar] (8)	NOT NULL,
	[RC_COD_PARTIDA]		[varchar] (10)	NOT NULL,
	[RC_COD_OPERACION]		[varchar] (5)	NOT NULL,
	[RC_ARCHIVO]			[varchar] (50)	NULL,
	[RC_FECHA_PROCESO]		[datetime]		NOT NULL,
	[RC_TOTAL_REGISTRO]		[int]			NOT NULL,
	[RC_TOTAL_DEBITO]		[decimal] (18, 2) NOT NULL,
	[RC_TOTAL_CREDITO]		[decimal] (18, 2) NOT NULL,
	[RC_TOTAL]				[decimal] (18, 2) NOT NULL,
	[RC_ESTATUS_LOTE]		[varchar] (10)		NOT NULL,
	[RC_COD_EVENTO]			[varchar] (10)		NULL,
	[RC_FECHA_CREACION]		[datetime]		NOT NULL,
	[RC_USUARIO_CREACION]	[varchar](8)	NOT NULL,
	[RC_FECHA_MOD]			[datetime]		NOT NULL,
	[RC_USUARIO_MOD]		[varchar](8)	NOT NULL,

 CONSTRAINT [PK_REGISTRO_CARGA] PRIMARY KEY CLUSTERED 
(
	[RC_COD_USUARIO], [RC_COD_PARTIDA], [RC_COD_OPERACION]		 ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_PARTIDAS]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_PARTIDAS]
GO

CREATE TABLE [dbo].[SAX_PARTIDAS](
[pa_COD_USUARIO]		[varchar]	(8)		NOT NULL,
[PA_COD_PARTIDA]		[varchar]	(10)	NOT NULL,
[PA_COD_OPERACION]		[varchar]	(5)		NOT NULL,
[PA_REGISTRO]			[int]				not null,
[PA_COD_EMPRESA]		[varchar]	(3)		NOT NULL,
[PA_FECHA_CARGA]		[datetime]			NOT NULL,
[PA_FECHA_TRX]			[datetime]			NOT NULL, 
[PA_CTA_CONTABLE]		[varchar]	(30)	NOT NULL,
[PA_CENTRO_COSTO]		[varchar]	(4)		NOT NULL,
[PA_COD_MONEDA]			[varchar]	(4)		NOT NULL,
[PA_IMPORTE]			[decimal]	(18, 2)		NOT NULL,
[PA_REFERENCIA]			[varchar]	(13)	NOT NULL,
[PA_EXPLICACION]		[varchar]	(700)	NOT NULL,
[PA_PLAN_ACCION]		[varchar]	(700)	NULL,
[PA_CONCEPTO_COSTO]		[varchar]	(7)		NULL,
[PA_CAMPO_1]			[varchar]	(50)	NULL,
[PA_CAMPO_2]			[varchar]	(50)	NULL,
[PA_CAMPO_3]			[varchar]	(50)	NULL,
[PA_CAMPO_4]			[varchar]	(50)	NULL,
[PA_CAMPO_5]			[varchar]	(50)	NULL,
[PA_CAMPO_6]			[varchar]	(50)	NULL,
[PA_CAMPO_7]			[varchar]	(50)	NULL,
[PA_CAMPO_8]			[varchar]	(50)	NULL,
[PA_CAMPO_9]			[varchar]	(50)	NULL,
[PA_CAMPO_10]			[varchar]	(50)	NULL,
[PA_CAMPO_11]			[varchar]	(50)	NULL,
[PA_CAMPO_12]			[varchar]	(50)	NULL,
[PA_CAMPO_13]			[varchar]	(50) NULL,
[PA_CAMPO_14]			[varchar]	(50) NULL,
[PA_CAMPO_15]			[varchar]	(50) NULL,
[PA_CAMPO_16]			[varchar]	(50) NULL,
[PA_CAMPO_17]			[varchar]	(50) NULL,
[PA_CAMPO_18]			[varchar]	(50) NULL,
[PA_CAMPO_19]			[varchar]	(50) NULL,
[PA_CAMPO_20]			[varchar]	(50) NULL,
[PA_CAMPO_21]			[varchar]	(50) NULL,
[PA_CAMPO_22]			[varchar]	(50) NULL,
[PA_CAMPO_23]			[varchar]	(50) NULL,
[PA_CAMPO_24]			[varchar]	(50) NULL,
[PA_CAMPO_25]			[varchar]	(50) NULL,
[PA_CAMPO_26]			[varchar]	(50) NULL,
[PA_CAMPO_27]			[varchar]	(50) NULL,
[PA_CAMPO_28]			[varchar]	(50) NULL,
[PA_CAMPO_29]			[varchar]	(50) NULL,
[PA_CAMPO_30]			[varchar]	(50) NULL,
[PA_CAMPO_31]			[varchar]	(50) NULL,
[PA_CAMPO_32]			[varchar]	(50) NULL,
[PA_CAMPO_33]			[varchar]	(50) NULL,
[PA_CAMPO_34]			[varchar]	(50) NULL,
[PA_CAMPO_35]			[varchar]	(50) NULL,
[PA_CAMPO_36]			[varchar]	(50) NULL,
[PA_CAMPO_37]			[varchar]	(50) NULL,
[PA_CAMPO_38]			[varchar]	(50) NULL,
[PA_CAMPO_39]			[varchar]	(50) NULL,
[PA_CAMPO_40]			[varchar]	(50) NULL,
[PA_CAMPO_41]			[varchar]	(50) NULL,
[PA_CAMPO_42]			[varchar]	(50) NULL,
[PA_CAMPO_43]			[varchar]	(50) NULL,
[PA_CAMPO_44]			[varchar]	(50) NULL,
[PA_CAMPO_45]			[varchar]	(50) NULL,
[PA_CAMPO_46]			[varchar]	(50) NULL,
[PA_CAMPO_47]			[varchar]	(50) NULL,
[PA_CAMPO_48]			[varchar]	(50) NULL,
[PA_CAMPO_49]			[varchar]	(50) NULL,
[PA_CAMPO_50]			[varchar]	(50) NULL,
[PA_FECHA_CREACION]		[datetime]		NOT NULL,
[PA_USUARIO_CREACION]	[varchar]	(8)		NOT NULL,
[PA_FECHA_MOD]			[datetime]			NULL,
[PA_USUARIO_MOD]		[varchar]	(8)		NULL,
[PA_FECHA_APROB]		[datetime]			NULL,
[PA_USUARIO_APROB]		[varchar]	(8)		NULL,
[PA_STATUS_PARTIDA]		[varchar]	(10)	NOT NULL,
[PA_APLIC_ORIGEN]		[varchar]   (10)	NULL,	
[PA_TIPO_CONCILIA]		[varchar]   (10)	NULL,
[PA_ESTADO_CONCILIA]	[varchar]   (10)	NULL,
[PA_IMPORTE_PENDIENTE]	[decimal]	(18, 2)		NULL,
[PA_COD_COMPROBANTE]	[varchar]   (10)		NULL,
[PA_FECHA_CONCILIA]		[datetime]			NULL,
[PA_FECHA_ANULACION]	[datetime]		NULL,
[PA_DIAS_ANTIGUEDAD]	[int]			NULL,
[PA_ORIGEN_REFERENCIA]	[varchar]  (10)		NULL,

 CONSTRAINT [PK_PARTIDAS] PRIMARY KEY CLUSTERED 
(
	[PA_COD_USUARIO], [PA_COD_PARTIDA],[PA_COD_OPERACION],[PA_REGISTRO]			 ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_ROLES]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_ROLES]
GO

CREATE TABLE [dbo].[SAX_ROLES](
	[RL_COD_ROL]			[char](5) NOT NULL,
	[RL_NOMBRE_ROL]			[varchar](30) NOT NULL,
	[RL_DESCRIPCION_ROL]	[varchar](60) NOT NULL,
	[RL_ESTATUS_ROL]		[char](1) NOT NULL,
	[RL_FECHA_CREACION]		[datetime] NOT NULL,
	[RL_USUARIO_CREACION]	[char](8) NOT NULL,
	[RL_FECHA_MOD]			[datetime] NULL,
	[RL_USUARIO_MOD]		[char](8) NULL,
 CONSTRAINT [PK_SAX_ROLES] PRIMARY KEY CLUSTERED 
(	[RL_COD_ROL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_USUARIO]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_USUARIO]
GO

CREATE TABLE [dbo].[SAX_USUARIO](
	[US_COD_USUARIO]		[varchar](8)	NOT NULL,
	[US_NOMBRE]				[varchar](80)	NOT NULL,
	[US_ACTIVO]				[char](1) 		NOT NULL,
	[US_FECHA_CREACION]		[datetime]		NOT NULL,
	[US_USUARIO_CREACION]	[varchar](8)	NOT NULL,
	[US_FECHA_MOD]			[datetime]		NULL,
	[US_USUARIO_MOD]		[varchar](8)	NULL,
	[US_ULTIMO_ACCESO]		[datetime]		NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[US_COD_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_USUARIO_AREA]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_USUARIO_AREA]
GO

CREATE TABLE [dbo].[SAX_USUARIO_AREA](
	[UA_COD_USUARIO]		[varchar](8) NULL,
	[UA_COD_AREA]			[varchar](5)	NULL,
	[UA_ESTATUS]			[char](1)	NULL,
	[UA_FECHA_CREACION]		[datetime]	NULL,
	[UA_USUARIO_CREACION]	[varchar](8) NULL,
	[UA_FECHA_MOD]			[datetime]	NULL,
	[UA_USUARIO_MOD]		[varchar](8) NULL
	
	 CONSTRAINT [PK_USUARIO_AREA] UNIQUE CLUSTERED 
	([UA_COD_USUARIO], [UA_COD_AREA] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF,	IGNORE_DUP_KEY = OFF, 	ALLOW_ROW_LOCKS  = ON, 	ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX IDX_USUARIO_AREA ON  SAX_USUARIO_AREA(UA_COD_USUARIO, UA_COD_AREA)
		
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_USUARIO_EMPRESA]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_USUARIO_EMPRESA]
GO

CREATE TABLE [dbo].[SAX_USUARIO_EMPRESA](
	[UE_COD_USUARIO]		[varchar](8) NULL,
	[UE_COD_EMPRESA]		[varchar](5)	NULL,
	[UE_ESTATUS]			[char](1)	NULL,
	[UE_FECHA_CREACION]		[datetime]	NULL,
	[UE_USUARIO_CREACION]	[varchar](8) NULL,
	[UE_FECHA_MOD]			[datetime]	NULL,
	[UE_USUARIO_MOD]		[varchar](8) NULL
	
	 CONSTRAINT [PK_USUARIO_EMPRESA] UNIQUE CLUSTERED 
	([UE_COD_USUARIO], [UE_COD_EMPRESA] ASC
	)WITH (PAD_INDEX  = OFF, 
	STATISTICS_NORECOMPUTE  = OFF, 
	IGNORE_DUP_KEY = OFF, 
	ALLOW_ROW_LOCKS  = ON, 
	ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
		
	CREATE NONCLUSTERED INDEX IDX_USUARIO_EMPRESA ON  SAX_USUARIO_EMPRESA(UE_COD_USUARIO, UE_COD_EMPRESA)
		
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SAX_USUARIO_ROL]') AND type in (N'U'))
DROP TABLE [dbo].[SAX_USUARIO_ROL]
GO

CREATE TABLE [dbo].[SAX_USUARIO_ROL](
	[UR_COD_USUARIO]		[varchar](8) not NULL,
	[UR_COD_ROL]			[varchar](5)	not NULL,
	[UR_ESTATUS]			[char](1)	not NULL,
	[UR_FECHA_CREACION]		[datetime]	not NULL,
	[UR_USUARIO_CREACION]	[varchar](8) not NULL,
	[UR_FECHA_MOD]			[datetime]	NULL,
	[UR_USUARIO_MOD]		[varchar](8) NULL
	
	 CONSTRAINT [PK_USUARIO_ROL] PRIMARY KEY CLUSTERED 
	([UR_COD_USUARIO] ASC
	
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX IDX_ROL ON SAX_USUARIO_ROL(UR_COD_USUARIO, UR_COD_ROL)
		
GO